# fly.toml app configuration file generated for puhelinluettelo-holy-wildflower-4543 on 2025-04-01T12:36:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'puhelinluettelo-holy-wildflower-4543'
primary_region = 'fra'

[build]
[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  strategy = "canary"

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
